
osx_image: xcode9
language: swift

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AnyFormatKit.xcworkspace -scheme AnyFormatKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
